"""
    Write a record to the 'User_Record1.csv' file.
    :param generated_word: The word generated by the function.
    :type generated_word: str
    :param count: The number of times the function has been called.
    :type count: int
    :param result: The result of the function.
    :type result: str
    """
import csv
from datetime import date
with open('User_Record.csv','w+') as f:
    r = csv.writer(f)
    r.writerow(['DATE','GENERATED WORD','COUNT','RESULT'])
    f.close()
"""r = csv.writer(f)
r.writerow(['DATE','GENERATED WORD','COUNT','RESULT'])
f.close()"""
def recorder(generated_word,count,result):
    with open("User_Record.csv","a+") as f_r:
        rec = csv.writer(f_r)
        if count < 3:
            rem = 'Great'
        elif count > 3 and count < 5:
            rem = 'Not bad'
        else:
            rem = 'Try har next time'
        
        l = [date.today(),generated_word,count,result,rem]
        rec.writerow(l)
    f_r.flush()
